import React from "react";
import NIEImage from "../assets/NIE.jpg";
import "../styles/Project.css";
function NIE() {
return (
    <div className="about">
    <div
        className="aboutTop"
        style={{ backgroundImage: `url(${NIEImage})` }}
    ></div>
    <div className="aboutBottom">
        <h1>NIE Monitoring</h1>
        <h2>Northern Ireland Electricity Summary</h2>
        <p>NIE uses Qlikview for application reporting. Atos runs first and second line support for Qlik, passing any third level support queries to V1. Version 1 supports the following applications:</p>
        <p>•Pricing </p>
        <p>•High Performing Human Resource</p>
        <p>•Speed of Service</p>
        <p>•MFS</p>
        <p>•RIGs</p>
        <p>•Financial RIGs</p>
        <p>•New Connections Application</p>
        <p>•Complaints</p>
        <p>•Market Messages</p>
        <h3>Environment Links</h3>
        <p>*We are not permitted to access the NIE Production Environment.  All work must be moved across by ATOS.</p>
        <table>
        <tr>
            <th>Environment</th>
            <th>Item</th>
            <th>Link</th>
            <th>Notes</th>
        </tr>
        <tr>
            <td>Development</td>
            <td>Qlik</td>
            <td>https://xceedium.nie.co.uk/index.php</td>
            <td>Only 2 users can RDP simultaneously</td>
        </tr>
        </table>
        <h2>Points of Contact</h2>
        <table>
        <tr>
            <th>Person</th>
            <th>Role</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Notes</th>
        </tr>
        <tr>
            <td>Leon Dorrity</td>
            <td>NIE Data Analyst</td>
            <td>Leon.Dorrity@nienetworks.co.uk</td>
            <td>+44 (0)7845 612004 / +44 (0)7899 067950</td>
            <td>Raises tickets related to RIGs primarily</td>
        </tr>
        <tr>
            <td>Hugh O'Neill</td>
            <td></td>
            <td>hugh.oneill@atos.net</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>David Peover</td>
            <td>ATOS Support Lead</td>
            <td>david.peover@atos.net</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>Chris Hamill</td>
            <td>ATOS Support Engineer</td>
            <td>christopher.hamill@atos.net </td>
            <td></td>
            <td>Our primary contact in ATOS.  Raises the vast majority of tickets</td>
        </tr>
        </table>
        <h2>How To Connect to NIE</h2>
        <p>Log in to Xcedium – Internet Explorer required and Java Download:</p>
        <p>https://xceedium.nie.co.uk/index.php</p>
        <p>Stage 1:<br></br>
        Enter user ID<br></br>
        Password is User Specific Pin plus the token generated by the Fob<br></br>
        Example:<br></br>
        User: HQDXG<br></br>
        Password: 9966*fob token*<br></br></p>
        <p>NB: You may have to add https://xceedium.nie.co.uk/ to the list of sites Java trusts.  Java security settings are in Windows Control Panel, under Java -&#62; Security. </p>
        <p><img src="/NIEDocs/NIE1.png" alt="Privileged Access Manager Login Screen"/></p>
        <p>Stage 2:<br></br>
        The next screen displays and RDP icon.<br></br>
        To launch click and enter the Username and Password, for example:<br></br>
        User:                     HQDXG<br></br>
        Password:            In 1Password<br></br>
        Domain:                Nie.co.uk<br></br></p>
        <p>Note: Sometimes this screen will flash or disappear behind other windows.  Minimising Internet Explorer should allow you to enter the info into the login popup. 
        You may also see an error ‘Unable To Connect To Back End Device’.  If this occurs, restart IE and try again.</p>
        <h2>How To Verify Qlik Issues</h2>
        <p>Most Qlik isues that come in will either be task failures or issues in charts / apps within the customer-facing Qlik environments. </p>
        <p>In order to verify / triage an issue in a chart, follow the below steps:</p>
        <p>1. Access the appropriate environment for the customer (referring to the below table)</p>
        <p>2. Navigate to the Qlik Access Point (QlikView) / Hub (Qlik Sense)</p>
        <p>3. Find the app / sheet / chart the customer has mentioned in their ticket.  If they haven’t been specific about this, go back and verify. </p>
        <p>4. Make any selections the customer has specified and observe the data to verify that the issue they are talking about is still occurring.
            If you don’t know which selections the customer is making, go back to them and request these, a full-screen screenshot of the issue can also be very helpful.</p>
            <h3>Replicating Issues In Dev</h3>
        <p>Once you have verified the customer’s issue, try to replicate it in Dev.  This is normally as simple as RDPing into the respective Dev server and reloading the app the customer is having issues with in QV Desktop or Qlik Sense Hub (depending on the customer).
            Data in Dev are normally transferred overnight, so should be correct as of the previous day.  If the issue isn’t in Dev, then it’s likely that the problem lies in the current day’s reloads.</p>
        <p>Once replicated, reach out to / pass on to L3 if the issue isn’t a quick fix (eg adding a field/re-running a task).</p>
        <h3>Troubleshooting / Quick Fixes</h3>
        <p>1. Check for task failures, often data can be wrong because it hasn’t updated.  The QMC will show you if there is a failed task associated with the app you are looking at. </p>
        <p>2. Check where the data comes from.  It could be that there are records missing either from a source DB or a user-editable Excel.  If this ends up being the case, ask the user to check their source data.
            For this a specific example is invaluable, so if the customer hasn’t provided one, go back and ask.</p>
        <p>NB: If the issue isn’t app / chart specific (eg an app isn’t loading or the system is down) check the server immediately and ensure all services are running.
            Logs are sometimes in specific locations, but are most likely in C:/ProgramData/QlikTech/&#60;Name Of Service&#62;/log/ for QlikView and available in the Operations Monitor in Qlik Sense Hub</p>
    </div>
    </div>
);
}

export default NIE;